name: Update Stock Heatmap Data

on:
  schedule:
    # 每15分钟运行一次
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # 允许在GitHub网站上手动触发此任务

jobs:
  warmup-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel warmup endpoint
        run: |
          curl --request GET \
          --url 'https://您的最终域名/api/warmup' \
          --header 'x-warmup-secret: ${{ secrets.WARMUP_SECRET }}'